### ISSUE TITLE
Make changes to import registry response model because of single mips report context requirement

### ISSUE THREAD

**Issue by darena-mhaque** [darena-solutions/mymipsscore-public#30]
It was determined that you should always have one mips report id context when importing a registry import file. This was how it always worked, but the wrong assumption was made where it was thought that the file was being imported to all mips reports the user has access to. This resulted in the wrong model being made.

The model that was implemented in #28 should be re-worked with this in mind, where there is exactly one mips report to import to.

**Comment by darena-dkuecker** [comment]
Please update the Gender enum as follows:

![image](https://user-images.githubusercontent.com/53532710/69373010-765a8f80-0c68-11ea-8a99-f739ab767dd5.png)

per FHIR standard R4, http://hl7.org/fhir/valueset-administrative-gender.html.

Also if the first character or full description can be used to map, it would be appreciated.
